# Generated by Django 4.2 on 2025-08-01 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habitapi', '0002_habit_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='status',
        ),
        migrations.AddField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
