# Generated by Django 4.2 on 2025-07-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
